__default__:
  time: "18000"
  partition : "main"
  job-name : "{rule}"
  output: "LOGS/SLURM/slurm-%j.%N-%x.out"
  error: "LOGS/SLURM/slurm-%j.%N-%x.err"
  #mail-type: "ALL"
  #mail-user: "user@address"
  account: \${{USER}}
  mem: 10000
